[theme]

# Primary color for interactive elements (buttons, sliders, etc.)
primaryColor = "#ff6f00ff"
# Main background color
backgroundColor = "#1a1a1aff"
# Background color for sidebar and containers
secondaryBackgroundColor = "#3d3d3d"
# Text color
textColor = "#ffffffff"
# Font family
font = "sans-serif"